### ISSUE TITLE
[Q] How to duplicate video on multiple monitors?

### ISSUE THREAD

**Issue by ghost** [Komorebi-Fork/komorebi#60] opened 2020-12-29 18:43 UTC
What are the configs to replicate the video wallpaper on multiple monitors?

**Default behavior** it stretches the video to fit all the screens (great) but sometimes I want to use 16:9 video without stretching

**Config file**
```
[Info]
WallpaperType=video
VideoFileName=video.mp4

[DateTime]
Visible=false
Parallax=false
MarginTop=0
MarginRight=0
MarginLeft=0
MarginBottom=0
RotationX=0
RotationY=0
RotationZ=0
Position=center
Alignment=center
AlwaysOnTop=true
Color=#dd22dd22dd22
Alpha=255
ShadowColor=#dd22dd22dd22
ShadowAlpha=255
TimeFont=Lato Light 30
DateFont=Lato Light 20
```

How do I replicate video on 2 or more monitors without stretching?

**Comment by Ev1lbl0w** [comment] 2020-12-30 12:07
Duplicate of #29; however, there's currently no way to have different configurations for different screens, that would be useful.

**Closed** 2024-03-04 11:03 UTC
