### ISSUE TITLE
[Bug] Crashing on Ubuntu 20.04

### ISSUE THREAD

**Issue by vleeuwenmenno** [Komorebi-Fork/komorebi#27] opened 2020-08-07 01:38 UTC
I'm running on Ubuntu 20.04 with a RX 5700 XT and a Ryzen 9 3900X 32GB 3733Mhz
It crashes 1-2s after launch, the v2.1 stays open but the wallpaper selector I cannot find.

I have no idea what I can supply to make it easier to debug this so please point me in the right direction.

EDIT:

Starting from terminal reveals the following error:
```
(komorebi:15075): Gdk-ERROR **: 03:39:49.287: The program 'komorebi' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadDrawable'.
  (Details: serial 593 error_code 160 request_code 152 (GLX) minor_code 29)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)

```

**Comment by vleeuwenmenno** [comment] 2020-08-07 01:52
Changing Main.vala line 70 to `int monitorCount = 1;` seems to solve the issue.
Limiting the monitors to 1 though, changing it to 2 also makes it crash.

**Comment by Kangie** [comment] 2020-08-07 06:48
@vleeuwenmenno check the --single-screen flag out. 

This appears to be related to a known bug when running Komorebi on certain dual-monitor setups.

**Comment by Kangie** [comment] 2020-08-07 06:50
Oh, and thanks for the feedback / bug report!

**Comment by Kangie** [comment] 2020-08-07 06:50
Oh, and thanks for the feedback / bug report!

**Comment by Ev1lbl0w** [comment] 2020-09-09 14:04
@vleeuwenmenno I'll close this issue as it's likely a duplicate of #18 and @Kangie has provided you a temporary solution.

**Closed by Ev1lbl0w** 2020-09-09 14:04 UTC
Labels: bug
